sudo: false

language: go

go:
  #- 1.9.x
  - 1.x

# Only clone the most recent commit.
git:
  depth: 1

install: true

notifications:
  email: false

before_install:
  - curl https://glide.sh/get | sh

before_script:
  - glide install

script:
  - cd pkg/boltstore/; go test -v